import React from "react";
import { FileText, ListChecks, CheckCircle, Users } from "lucide-react";

const HowItWorks = () => {
  const steps = [
    {
      icon: <FileText />,
      title: "Sign Up",
      description:
        "Scale up to $2 Millions in simulated we do not deduct payout amounts from your balance when you request it.",
    },
    {
      icon: <ListChecks />,
      title: "Evaluate",
      description:
        "As soon as you receive your login credentials, you are free to trade and work towards achieving the profit target to progress to the next stage.",
    },
    {
      icon: <CheckCircle />,
      title: "Verification",
      description:
        "At this stage, you'll need to submit your documents for KYC verification. Once KYC is completed, we'll proceed to provide you with the login for the simulated funded account.",
    },
    {
      icon: <Users />,
      title: "Funded",
      description:
        "At this stage, you are ready to start earning. As a Quick Funded customer, you'll enjoy the benefit of receiving 85% of your profit share on your first withdrawal.",
    },
  ];

  return (
    <div className=" p-8">
      <div className="">
        <h1
          className="text-5xl font-bold bg-clip-text 
                bg-[linear-gradient(90deg,#88B92F_0%,#109523_100%)] text-transparent mb-4"
        >
          How It Works
        </h1>
      </div>

      {/* <p className="text-gray-600 mb-8">
        Increase the initial balance of your trading account to a scaled balance
        using the profits generated by your strategy; we do not deduct payout
        amounts
      </p> */}
      {/* <button className="bg-green-500 text-white px-6 py-2 rounded-full mb-8">
        Connect With Us
      </button> */}
      <div className="grid grid-cols-1 md:grid-cols-2 py-16 lg:grid-cols-4 gap-8">
        {steps.map((step, index) => (
          <div key={index} className="flex flex-col items-center text-center">
            <div
              className={`w-16 h-16 rounded-full flex items-center justify-center mb-4 ${
                index === 0
                  ? "bg-green-500"
                  : index === 1
                  ? "bg-blue-500"
                  : index === 2
                  ? "bg-orange-500"
                  : "bg-purple-500"
              }`}
            >
              {React.cloneElement(step.icon, {
                className: "text-white",
                size: 24,
              })}
            </div>
            <h3 className="text-xl font-semibold mb-2">{step.title}</h3>
            <p className="text-gray-600">{step.description}</p>
          </div>
        ))}
      </div>
    </div>
  );
};

export default HowItWorks;
